// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netIPAM.DBContexts;

#nullable disable

namespace cIPAM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316202946_updateSettings")]
    partial class updateSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("netIPAM.Models.Account.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8b5abfdb-2cfe-405d-aca2-4d884fa29b9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55ddd299-2b34-4665-aea6-d3a5b6f339f6",
                            Email = "admin@local.lan",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL.LAN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGM/ll7G62x2i5K84HUeA1LRTrMucZ6zPbAIMxnNEgg2KCVy9remI9mlliHU2tpHrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9c78a916-aa9e-4862-b40b-8563a3ae874a",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("netIPAM.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "siteTitle",
                            Type = 0,
                            Value = "netIPAM address management"
                        },
                        new
                        {
                            Id = 2,
                            Name = "siteDomain",
                            Type = 0,
                            Value = "domain.local"
                        },
                        new
                        {
                            Id = 3,
                            Name = "siteURL",
                            Type = 0,
                            Value = "http://yourpublicurl.com"
                        },
                        new
                        {
                            Id = 4,
                            Name = "siteLoginText",
                            Type = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            Name = "permissionPropagate",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 6,
                            Name = "vlanMax",
                            Type = 1,
                            Value = "4096"
                        },
                        new
                        {
                            Id = 7,
                            Name = "maintaneanceMode",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 8,
                            Name = "siteAdminName",
                            Type = 0,
                            Value = "Sysadmin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "siteAdminMail",
                            Type = 0,
                            Value = "admin@domain.local"
                        },
                        new
                        {
                            Id = 10,
                            Name = "api",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 11,
                            Name = "enableIPrequests",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 12,
                            Name = "enableVRF",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 13,
                            Name = "enableNAT",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 14,
                            Name = "enablePowerDNS",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 15,
                            Name = "enableDHCP",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 16,
                            Name = "enableFirewallZones",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 17,
                            Name = "enableDNSresolving",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 18,
                            Name = "tempShare",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 19,
                            Name = "enableChangelog",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 20,
                            Name = "enableMulticast",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 21,
                            Name = "enableThreshold",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 22,
                            Name = "enableRACK",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 23,
                            Name = "enableCircuits",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 24,
                            Name = "enableLocations",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 25,
                            Name = "enableSNMP",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 26,
                            Name = "enablePSNT",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 27,
                            Name = "enableCustomers",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 28,
                            Name = "enableRouting",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 29,
                            Name = "updateTags",
                            Type = 2,
                            Value = "False"
                        },
                        new
                        {
                            Id = 30,
                            Name = "enforceUnique",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 31,
                            Name = "vlanDuplicate",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 32,
                            Name = "decodeMAC",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 33,
                            Name = "enableVaults",
                            Type = 2,
                            Value = "True"
                        },
                        new
                        {
                            Id = 34,
                            Name = "passkeys",
                            Type = 2,
                            Value = "True"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("netIPAM.Models.Account.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("netIPAM.Models.Account.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("netIPAM.Models.Account.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netIPAM.Models.Account.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("netIPAM.Models.Account.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
